name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest  # Change the runs-on field to a GitHub-hosted runner

    steps:

    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker in Docker
        uses: docker/setup-docker@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lnsdockerhub/lnscicd:${{ github.sha }}
          
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
           # Stop and remove the container if it exists
            if docker ps -a | grep lnscicd; then
            docker stop lnscicd || true
            docker rm lnscicd || true
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/lnscicd:${{ github.sha }}
            docker run -d --name lnscicd -p 80:80 ${{ secrets.DOCKER_USERNAME }}/lnscicd:${{ github.sha }}
